[package]
name = "kfuzz"
version = "0.1.0"
authors = ["Kevin Laeufer <ekiwi@berkeley.edu>"]

[dependencies]
libc = "0.2.21"
time = "0.1"
twox-hash = "1.1.0"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
colored = "1.6"
prettytable-rs = "^0.6"
