name: rfuzz Instrumentation and Harness CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cache:
    name: Instrument Caches
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y build-essential meson pkg-config verilator python3-toml

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: ICache
      run: make FIR=ICache.fir DUT=ICache bin

    - name: ICache w/ Coverage
      run: make FIR=ICacheCover.fir DUT=ICache bin

    - name: Non-Blocking Data Cache
      run: make FIR=NonBlockingDCache.fir DUT=NonBlockingDCache bin


  sodor:
    name: Instrument Sodor Cores
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y build-essential meson pkg-config verilator python3-toml

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Sodor 1-Stage
      run: make FIR=Sodor1Stage.fir DUT=Sodor1Stage bin

    - name: Sodor 3-Stage
      run: make FIR=Sodor3Stage.fir DUT=Sodor3Stage bin

    - name: Sodor 5-Stage
      run: make FIR=Sodor5Stage.fir DUT=Sodor5Stage bin


  peripheral:
    name: Instrument TileLink Peripherals
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y build-essential meson pkg-config verilator python3-toml

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: I2C Peripheral
      run: make FIR=TLI2C.fir DUT=TLI2C bin

    - name: PWM Peripheral
      run: make FIR=TLPWM.fir DUT=TLPWM bin

    - name: SPI Peripheral
      run: make FIR=TLSPI.fir DUT=TLSPI bin

    - name: UART Peripheral
      run: make FIR=TLUART.fir DUT=TLUART bin


  fft:
    name: Instrument FFT
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y build-essential meson pkg-config verilator python3-toml

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: FFT Small
      run: make FIR=FFTSmall.fir DUT=FFTSmall bin


  rocket:
    name: Instrument Rocket Chip w/o Verilator Compilation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y python3-toml

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Rocket Chip Tile
      run: make FIR=RocketTile.fir DUT=RocketTile build/RocketTile_VHarness.v

